Actor.where(name: 'Leo').first_or_create!(name: 'Leo')
Actor.where(name: 'Tayyab').first_or_create!(name: 'Tayyab')
Actor.where(name: 'Hamza').first_or_create!(name: 'Hamza')
Actor.where(name: 'NPH').first_or_create!(name: 'NPH')
Actor.where(name: 'Joey').first_or_create!(name: 'Joey')
